import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  introSidebar: ['intro', 'writing-guideline'],
  danxiAppSidebar: [
    {
      type: 'autogenerated',
      dirName: 'danxi',
    }
  ],
  maintenanceSidebar: [
    {
      type: 'autogenerated',
      dirName: 'maintenance',
    }
  ]
};

export default sidebars;
