import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  introSidebar: ['intro', 'writing-guideline', {
    'Document Basic': [
      {
        type: 'autogenerated',
        dirName: 'tutorial-basics',
      }
    ],
    'Document Extra': [
      {
        type: 'autogenerated',
        dirName: 'tutorial-extras',
      }
    ],
  }],
  danxiAppSidebar: [
    {
      type: 'autogenerated',
      dirName: 'danxi',
    }
  ],
  maintenanceSidebar: [
    {
      type: 'autogenerated',
      dirName: 'maintenance',
    }
  ]
};

export default sidebars;
